'use strict';

import Enum from './Enum.mjs';

class ArrlSectionEnum extends Enum {

    constructor() {
        super([
            'Abbreviation',
            'AL',
            'AK',
            'AB',
            'AR',
            'AZ',
            'BC',
            'CO',
            'CT',
            'DE',
            'EB',
            'EMA',
            'ENY',
            'EPA',
            'EWA',
            'GA',
            'GH',
            'GTA',
            'ID',
            'IL',
            'IN',
            'IA',
            'KS',
            'KY',
            'LAX',
            'LA',
            'ME',
            'MB',
            'MAR',
            'MDC',
            'MI',
            'MN',
            'MS',
            'MO',
            'MT',
            'NE',
            'NV',
            'NB',
            'NH',
            'NM',
            'NLI',
            'NL',
            'NC',
            'ND',
            'NTX',
            'NFL',
            'NNJ',
            'NNY',
            'NT',
            'NWT',
            'NS',
            'OH',
            'OK',
            'ON',
            'ONE',
            'ONN',
            'ONS',
            'ORG',
            'OR',
            'PAC',
            'PE',
            'PR',
            'QC',
            'RI',
            'SV',
            'SDG',
            'SF',
            'SJV',
            'SB',
            'SCV',
            'SK',
            'SC',
            'SD',
            'STX',
            'SFL',
            'SNJ',
            'TN',
            'TER',
            'VI',
            'UT',
            'VT',
            'VA',
            'WCF',
            'WTX',
            'WV',
            'WMA',
            'WNY',
            'WPA',
            'WWA',
            'WI',
            'WY',
        ]);
    }

}

export default ArrlSectionEnum;
