'use strict';

import Enum from './Enum.mjs';

class CreditEnum extends Enum {

    constructor() {
        super([
            'CQDX',
            'CQDX_BAND',
            'CQDX_MODE',
            'CQDX_MOBILE',
            'CQDX_QRP',
            'CQDX_SATELLITE',
            'CQDXFIELD',
            'CQDXFIELD_BAND',
            'CQDXFIELD_MODE',
            'CQDXFIELD_MOBILE',
            'CQDXFIELD_QRP',
            'CQDXFIELD_SATELLITE',
            'CQWAZ_MIXED',
            'CQWAZ_BAND',
            'CQWAZ_MODE',
            'CQWAZ_SATELLITE',
            'CQWAZ_EME',
            'CQWAZ_MOBILE',
            'CQWAZ_QRP',
            'CQWPX',
            'CQWPX_BAND',
            'CQWPX_MODE',
            'DXCC',
            'DXCC_BAND',
            'DXCC_MODE',
            'DXCC_SATELLITE',
            'EAUSTRALIA',
            'ECANADA',
            'ECOUNTY_STATE',
            'EDX',
            'EDX100',
            'EDX100_BAND',
            'EDX100_MODE',
            'EECHOLINK50',
            'EGRID_BAND',
            'EGRID_SATELLITE',
            'EPFX300',
            'EPFX300_MODE',
            'EWAS',
            'EWAS_BAND',
            'EWAS_MODE',
            'EWAS_SATELLITE',
            'EZ40',
            'EZ40_MODE',
            'FFMA',
            'IOTA',
            'IOTA_BASIC',
            'IOTA_CONT',
            'IOTA_GROUP',
            'RDA',
            'USACA',
            'VUCC_BAND',
            'VUCC_SATELLITE',
            'WAB',
            'WAC',
            'WAC_BAND',
            'WAE',
            'WAE_BAND',
            'WAE_MODE',
            'WAIP',
            'WAIP_BAND',
            'WAIP_MODE',
            'WAS',
            'WAS_BAND',
            'WAS_EME',
            'WAS_MODE',
            'WAS_NOVICE',
            'WAS_QRP',
            'WAS_SATELLITE',
            'WITUZ',
            'WITUZ_BAND',
        ]);
    }

}

export default CreditEnum;
