'use strict';

module.exports = {
    "CQDX": "CQ Magazine DX Mixed",
    "CQDX_BAND": "CQ Magazine DX Band",
    "CQDX_MODE": "CQ Magazine DX Mode",
    "CQDX_MOBILE": "CQ Magazine DX Mobile",
    "CQDX_QRP": "CQ Magazine DX QRP",
    "CQDX_SATELLITE": "CQ Magazine DX Satellite",
    "CQDXFIELD": "CQ Magazine DX Field Mixed",
    "CQDXFIELD_BAND": "CQ Magazine DX Field Band",
    "CQDXFIELD_MODE": "CQ Magazine DX Field Mode",
    "CQDXFIELD_MOBILE": "CQ Magazine DX Field Mobile",
    "CQDXFIELD_QRP": "CQ Magazine DX Field QRP",
    "CQDXFIELD_SATELLITE": "CQ Magazine DX Field Satellite",
    "CQWAZ_MIXED": "CQ Magazine Worked All Zones (WAZ) Mixed",
    "CQWAZ_BAND": "CQ Magazine Worked All Zones (WAZ) Band",
    "CQWAZ_MODE": "CQ Magazine Worked All Zones (WAZ) Mode",
    "CQWAZ_SATELLITE": "CQ Magazine Worked All Zones (WAZ) Satellite",
    "CQWAZ_EME": "CQ Magazine Worked All Zones (WAZ) EME",
    "CQWAZ_MOBILE": "CQ Magazine Worked All Zones (WAZ) Mobile",
    "CQWAZ_QRP": "CQ Magazine Worked All Zones (WAZ) QRP",
    "CQWPX": "CQ Magazine WPX Mixed",
    "CQWPX_BAND": "CQ Magazine WPX Band",
    "CQWPX_MODE": "CQ Magazine WPX Mode",
    "DXCC": "ARRL DX Century Club (DXCC) Mixed",
    "DXCC_BAND": "ARRL DX Century Club (DXCC) Band",
    "DXCC_MODE": "ARRL DX Century Club (DXCC) Mode",
    "DXCC_SATELLITE": "ARRL DX Century Club (DXCC) Satellite",
    "EAUSTRALIA": "eQSL eAustralia Mixed",
    "ECANADA": "eQSL eCanada Mixed",
    "ECOUNTY_STATE": "eQSL eCounty State",
    "EDX": "eQSL eDX Mixed",
    "EDX100": "eQSL eDX100 Mixed",
    "EDX100_BAND": "eQSL eDX100 Band",
    "EDX100_MODE": "eQSL eDX100 Mode",
    "EECHOLINK50": "eQSL eEcholink50 Echolink",
    "EGRID_BAND": "eQSL eGrid Band",
    "EGRID_SATELLITE": "eQSL eGrid Satellite",
    "EPFX300": "eQSL ePfx300 Mixed",
    "EPFX300_MODE": "eQSL ePfx300 Mode",
    "EWAS": "eQSL eWAS Mixed",
    "EWAS_BAND": "eQSL eWAS Band",
    "EWAS_MODE": "eQSL eWAS Mode",
    "EWAS_SATELLITE": "eQSL eWAS Satellite",
    "EZ40": "eQSL eZ40 Mixed",
    "EZ40_MODE": "eQSL eZ40 Mode",
    "FFMA": "ARRL Fred Fish Memorial Award (FFMA) Mixed",
    "IOTA": "RSGB Islands on the Air (IOTA) Mixed",
    "IOTA_BASIC": "RSGB Islands on the Air (IOTA) Mixed",
    "IOTA_CONT": "RSGB Islands on the Air (IOTA) Continent",
    "IOTA_GROUP": "RSGB Islands on the Air (IOTA) Group",
    "RDA": "TAG Russian Districts Award (RDA) Mixed",
    "USACA": "CQ Magazine United States of America Counties (USA-CA) Mixed",
    "VUCC": "ARRL VHF/UHF Century Club Program (VUCC)",
    "VUCC_BAND": "ARRL VHF/UHF Century Club Program (VUCC) Band",
    "VUCC_SATELLITE": "ARRL VHF/UHF Century Club Program (VUCC) Satellite",
    "WAB": "WAB AG Worked All Britain (WAB) Mixed",
    "WAC": "IARU Worked All Continents (WAC) Mixed",
    "WAC_BAND": "IARU Worked All Continents (WAC) Band",
    "WAE": "DARC Worked All Europe (WAE) Mixed",
    "WAE_BAND": "DARC Worked All Europe (WAE) Band",
    "WAE_MODE": "DARC Worked All Europe (WAE) Mode",
    "WAIP": "ARI Worked All Italian Provinces (WAIP) Mixed",
    "WAIP_BAND": "ARI Worked All Italian Provinces (WAIP) Band",
    "WAIP_MODE": "ARI Worked All Italian Provinces (WAIP) Mode",
    "WAS": "ARRL Worked All States (WAS) Mixed",
    "WAS_BAND": "ARRL Worked All States (WAS) Band",
    "WAS_EME": "ARRL Worked All States (WAS) EME",
    "WAS_MODE": "ARRL Worked All States (WAS) Mode",
    "WAS_NOVICE": "ARRL Worked All States (WAS) Novice",
    "WAS_QRP": "ARRL Worked All States (WAS) QRP",
    "WAS_SATELLITE": "ARRL Worked All States (WAS) Satellite",
    "WITUZ": "RSGB Worked ITU Zones (WITUZ) Mixed",
    "WITUZ_BAND": "RSGB Worked ITU Zones (WITUZ) Band",
};
