'use strict';

import Enum from './Enum.mjs';

class ModeEnum extends Enum {

    constructor() {
        super([
            'AM',
            'ARDOP',
            'ATV',
            'CHIP',
            'CLO',
            'CONTESTI',
            'CW',
            'DIGITALVOICE',
            'DOMINO',
            'DYNAMIC',
            'FAX',
            'FM',
            'FSK441',
            'FSK',
            'FT8',
            'HELL',
            'ISCAT',
            'JT4',
            'JT6M',
            'JT9',
            'JT44',
            'JT65',
            'MFSK',
            'MSK144',
            'MTONE',
            'MT63',
            'OLIVIA',
            'OPERA',
            'PAC',
            'PAX',
            'PKT',
            'PSK',
            'PSK2K',
            'Q15',
            'QRA64',
            'ROS',
            'RTTY',
            'RTTYM',
            'SSB',
            'SSTV',
            'T10',
            'THOR',
            'THRB',
            'TOR',
            'V4',
            'VOI',
            'WINMOR',
            'WSPR',
        ], [
            'AMTORFEC',
            'ASCI',
            'C4FM',
            'CHIP64',
            'CHIP128',
            'DOMINOF',
            'DSTAR',
            'FMHELL',
            'FSK31',
            'GTOR',
            'HELL80',
            'HFSK',
            'JT4A',
            'JT4B',
            'JT4C',
            'JT4D',
            'JT4E',
            'JT4F',
            'JT4G',
            'JT65A',
            'JT65B',
            'JT65C',
            'MFSK8',
            'MFSK16',
            'PAC2',
            'PAC3',
            'PAX2',
            'PCW',
            'PSK10',
            'PSK31',
            'PSK63',
            'PSK63F',
            'PSK125',
            'PSKAM10',
            'PSKAM31',
            'PSKAM50',
            'PSKFEC31',
            'PSKHELL',
            'QPSK31',
            'QPSK63',
            'QPSK125',
            'THRBX',

        ]);
    }

}

export default ModeEnum;
