'use strict';

import Enum from './Enum.mjs';

class SubmodeEnum extends Enum {

    constructor() {
        super([
            '8PSK125',
            '8PSK125F',
            '8PSK125FL',
            '8PSK250',
            '8PSK250F',
            '8PSK250FL',
            '8PSK500',
            '8PSK500F',
            '8PSK1000',
            '8PSK1000F',
            '8PSK1200F',
            'AMTORFEC',
            'ASCI',
            'C4FM',
            'CHIP64',
            'CHIP128',
            'DMR',
            'DOM-M',
            'DOM4',
            'DOM5',
            'DOM8',
            'DOM11',
            'DOM16',
            'DOM22',
            'DOM44',
            'DOM88',
            'DOMINOEX',
            'DOMINOF',
            'DSTAR',
            'FMHELL',
            'FREEDV',
            'FSK31',
            'FSKH105',
            'FSKH245',
            'FSKHELL',
            'FSQCALL',
            'FST4',
            'FST4W',
            'FT4',
            'GTOR',
            'HELL80',
            'HELLX5',
            'HELLX9',
            'HFSK',
            'ISCAT-A',
            'ISCAT-B',
            'JS8',
            'JT4A',
            'JT4B',
            'JT4C',
            'JT4D',
            'JT4E',
            'JT4F',
            'JT4G',
            'JT9-1',
            'JT9-2',
            'JT9-5',
            'JT9-10',
            'JT9-30',
            'JT9A',
            'JT9B',
            'JT9C',
            'JT9D',
            'JT9E',
            'JT9E FAST',
            'JT9F',
            'JT9F FAST',
            'JT9G',
            'JT9G FAST',
            'JT9H',
            'JT9H FAST',
            'JT65A',
            'JT65B',
            'JT65B2',
            'JT65C',
            'JT65C2',
            'JTMS',
            'LSB',
            'M17',
            'MFSK4',
            'MFSK8',
            'MFSK11',
            'MFSK16',
            'MFSK22',
            'MFSK31',
            'MFSK32',
            'MFSK64',
            'MFSK64L',
            'MFSK128',
            'MFSK128L',
            'NAVTEX',
            'OLIVIA 4/125',
            'OLIVIA 4/250',
            'OLIVIA 8/250',
            'OLIVIA 8/500',
            'OLIVIA 16/500',
            'OLIVIA 16/1000',
            'OLIVIA 32/1000',
            'OPERA-BEACON',
            'OPERA-QSO',
            'PAC2',
            'PAC3',
            'PAC4',
            'PAX2',
            'PCW',
            'PSK10',
            'PSK31',
            'PSK63',
            'PSK63F',
            'PSK63RC10',
            'PSK63RC20',
            'PSK63RC32',
            'PSK63RC4',
            'PSK63RC5',
            'PSK125',
            'PSK125RC10',
            'PSK125RC12',
            'PSK125RC16',
            'PSK125RC4',
            'PSK125RC5',
            'PSK250',
            'PSK250RC2',
            'PSK250RC3',
            'PSK250RC5',
            'PSK250RC6',
            'PSK250RC7',
            'PSK500',
            'PSK500RC2',
            'PSK500RC3',
            'PSK500RC4',
            'PSK800RC2',
            'PSK1000',
            'PSK1000RC2',
            'PSKAM10',
            'PSKAM31',
            'PSKAM50',
            'PSKFEC31',
            'PSKHELL',
            'QPSK31',
            'Q65',
            'QPSK63',
            'QPSK125',
            'QPSK250',
            'QPSK500',
            'QRA64A',
            'QRA64B',
            'QRA64C',
            'QRA64D',
            'QRA64E',
            'ROS-EME',
            'ROS-HF',
            'ROS-MF',
            'SCAMP_FAST',
            'SCAMP_OO',
            'SCAMP_OO_SLW',
            'SCAMP_SLOW',
            'SCAMP_VSLOW',
            'SIM31',
            'SITORB',
            'SLOWHELL',
            'THOR-M',
            'THOR4',
            'THOR5',
            'THOR8',
            'THOR11',
            'THOR16',
            'THOR22',
            'THOR25X4',
            'THOR50X1',
            'THOR50X2',
            'THOR100',
            'THRBX',
            'THRBX1',
            'THRBX2',
            'THRBX4',
            'THROB1',
            'THROB2',
            'THROB4',
            'USB',
            'VARA HF',
            'VARA SATELLITE',
            'VARA FM 1200',
            'VARA FM 9600',
        ]);
    }

}

export default SubmodeEnum;
